import fsExtra from "fs-extra";
import { resolve } from "path";

export async function* getEmptyDirectoriesRecursively(directory: string): AsyncIterable<string> {
  const entries = await fsExtra.readdir(directory, { withFileTypes: true });
  if (entries.length == 0) {
    yield directory;
  }
  for (const entry of entries) {
    const result = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      yield* getEmptyDirectoriesRecursively(result);
    }
  }
}

/**
 * This functions recurses over all the bindings generated by TypeChain, but excludes the
 * "factories" directory from the search.
 */
export async function* getFilesRecursively(directory: string): AsyncIterable<string> {
  const entries = await fsExtra.readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    const result = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      // Do not recurse into the "factories" directory
      if (entry.name === "factories") {
        continue;
      }
      yield* getFilesRecursively(result);
    } else {
      yield result;
    }
  }
}
