import fsExtra from "fs-extra";
import { resolve } from "path";

/**
 * This functions recurses over all the bindings generated by TypeChain, but
 * excludes the "factories" directory from the search.
 */
export async function* getFilesRecursively(dir: string): AsyncIterable<string> {
  const entries = await fsExtra.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const result = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      // Do not recurse into the "factories" directory
      if (entry.name === "factories") {
        continue;
      }
      yield* getFilesRecursively(result);
    } else {
      yield result;
    }
  }
}
